#
# MAKEFILE for nvr library
#
GLEWDIR = $(VISIO_GLEW_TOP)
VFRDIR = ../../vfr/dist

CFLAGS = /D_WINDOWS /DWINDOWS /W3 /GR \
 /O1 /DNDEBUG /FD /EHsc /MD \
 /I$(VFRDIR)/include /I$(GLEWDIR)/include \
 /DGL_GLEXT_PROTOTYPES /D_WIN32 /D_WIN64

OBJS =	nvrBspTree.obj \
	nvrBrick.obj \
	nvrBrickSorter.obj \
	nvrOrthoSliceBrick.obj \
	nvrRender.obj \
	nvrOglExt.obj \
	SimpleVolume.obj \
	CropReadVolume.obj \

TARGET = nvr.lib

CXX = cl -nologo -c
AR = lib /NOLOGO
LINK = link
INSTALL = copy

.SUFFIXES: .cpp .obj

.cpp.obj:
	$(CXX) $(CFLAGS) $<


nvr.lib : $(OBJS)
	$(AR) -out:$@ $** 

install : $(TARGET)
	if not exist "..\lib" mkdir "..\lib"
	$(INSTALL) $(TARGET) ..\lib\

clean : 
	-@erase *.obj

distclean : clean
	-@erase $(TARGET) vc*0.*

